// lib/onchain.js — Feature 10: On-chain Proof Panel data layer.
//
// Presentation-only. Does NOT talk to the chain, does NOT execute forge, and
// does NOT track anything wallet.js/escrow calls don't already produce — it
// just formats already-happening blockchain activity (tx hashes returned by
// lib/wallet.js's escrow calls) for display, the same way lib/tips.js is a
// thin in-memory store for tips the app already generates.

import fs from 'bare-fs'
import path from 'bare-path'

const SEPOLIA_CHAIN_ID = 11155111 // same network wallet.js's SEPOLIA_CHAIN_ID targets
const EXPLORER_BASE = 'https://sepolia.etherscan.io'

export function getNetworkInfo () {
  return { name: 'Sepolia Testnet', chainId: SEPOLIA_CHAIN_ID }
}

/** Build a Sepolia Etherscan tx URL from a hash — never hardcoded, always derived. */
export function getExplorerTxUrl (hash) {
  if (!hash) return null
  return `${EXPLORER_BASE}/tx/${hash}`
}

/** Build a Sepolia Etherscan address URL — never hardcoded, always derived. */
export function getExplorerAddressUrl (address) {
  if (!address) return null
  return `${EXPLORER_BASE}/address/${address}`
}

// Transaction types this panel knows how to label. Reunite Refund is included
// for forward-compatibility with lib/wallet.js's existing escrowRefund() (no
// caller wires it up for Reunite today — only compute jobs currently trigger
// a refund path) so the panel never shows a raw/unlabeled type if that changes.
export const TX_TYPES = Object.freeze([
  'Reunite Deposit', 'Reunite Release', 'Reunite Refund',
  'Compute Deposit', 'Compute Release', 'Compute Refund'
])

/**
 * Normalize a transaction record for display — fills in an explorer URL and
 * defaults, never throws on partial input.
 * @param {{hash:string, type:string, timestamp?:number, status?:string}} entry
 */
export function formatTxEntry (entry) {
  const hash = (entry && entry.hash) || null
  return {
    hash,
    type: (entry && entry.type) || 'Unknown',
    timestamp: (entry && entry.timestamp) || Date.now(),
    status: (entry && entry.status) || 'confirmed',
    explorerUrl: getExplorerTxUrl(hash)
  }
}

// ─── Rolling transaction history (last 20) ────────────────────────────────────
// Mirrors lib/tips.js's addTip/getAllTips in-memory-store pattern — no new
// storage architecture introduced.
const HISTORY_LIMIT = 20
const txHistory = [] // newest first

/**
 * Trim a history array down to the rolling window — pure function, exported
 * so it can be unit tested independent of the module-level store.
 * @param {Array} history
 * @param {number} [limit]
 */
export function trimHistory (history, limit = HISTORY_LIMIT) {
  return history.slice(0, limit)
}

/**
 * Record a new on-chain transaction (called right after an existing
 * escrowDeposit/escrowConfirm/escrowRefund/computeEscrow* call resolves — this
 * does not perform or duplicate any transaction logic, only records the
 * result already returned by wallet.js).
 * @param {string} type - one of TX_TYPES
 * @param {string} hash
 * @param {string} [status]
 * @returns {Object|null} the formatted entry, or null if there's no hash to record
 */
export function recordTx (type, hash, status = 'confirmed') {
  if (!hash) return null
  const entry = formatTxEntry({ type, hash, status, timestamp: Date.now() })
  txHistory.unshift(entry)
  const trimmed = trimHistory(txHistory, HISTORY_LIMIT)
  txHistory.length = 0
  txHistory.push(...trimmed)
  return entry
}

/** @returns {Array} shallow copy of the current rolling history, newest first */
export function getTxHistory () {
  return txHistory.slice()
}

// ─── Static Foundry test/build metadata ───────────────────────────────────────
// Read-only snapshot generated by `forge test` + `forge build` (see
// contracts/foundry-report.json). Electron/backend never executes forge — this
// only reads the JSON file already written to disk.
let cachedReport = null

export function getFoundryReport () {
  if (cachedReport) return cachedReport
  try {
    const reportPath = path.join('contracts', 'foundry-report.json')
    const raw = fs.readFileSync(reportPath, 'utf8')
    cachedReport = JSON.parse(raw)
  } catch (err) {
    // Never fail the panel over a missing/unreadable metadata file.
    cachedReport = {
      testsPassing: null,
      gasOptimized: null,
      deploymentSizeBytes: null,
      deploymentGas: null,
      note: 'foundry-report.json unavailable'
    }
  }
  return cachedReport
}
